
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: chat
spec: 
  selector: 
    matchLabels: 
      app: chat
  replicas: 1 
  template: 
    metadata: 
      labels: 
        app: chat
    spec: 
      containers: 
      - name: chat
        image: ocebr/yoloproto:1.4
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 9000

--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: chat-service 
spec: 
  selector: 
    app: chat
  type: NodePort 
  ports: 
    - protocol: TCP 
      port: 9000
      nodePort: 30801
      targetPort: 9000