apiVersion: v1 
kind: ConfigMap 
metadata:  
  name: enrolement-config-file 
data:  
  .env: |
    HOST=0.0.0.0
    PORT=8082
    RUST_LOG=DEBUG
    DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgresdb
    SECRET_KEY=la-sercret-key
    JWT_SECRET=jwt-secret-key

--- 

apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: enrolement 
spec: 
  selector: 
    matchLabels: 
      app: enrolement 
  replicas: 1 
  template: 
    metadata: 
      labels: 
        app: enrolement 
    spec: 

      volumes:
        - name: enrolement-config-file-volume
          configMap: 
            name: enrolement-config-file 


      containers: 
      - name: enrolement 
        image: ocebr/enrolement:light
        imagePullPolicy: Always
        ports: 
        - containerPort: 8082
        volumeMounts:
          - name: enrolement-config-file-volume
            mountPath: /app/.env
            subPath: .env

--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: enrolement-service 
spec: 
  selector: 
    app: enrolement 
  type: NodePort 
  ports: 
    - protocol: TCP 
      port: 8082 
      nodePort: 30501
      targetPort: 8082 