apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #nginx.ingress.kubernetes.io/app-root: /
    nginx.ingress.kubernetes.io/use-proxy-protocol: "false"
  name: yolo-ingress
  namespace: default
spec:
  tls:
    - hosts:
      - yoloooo.com
      secretName: yolo
  rules:
  - host: yoloooo.com
    http:
      paths:
      - path: /signin
        pathType: Prefix
        backend:
          service:
            name: users-pass-service 
            port:
              number: 8080
  - host: yoloooo.com
    http:
      paths:
      - path: /signup
        pathType: Prefix
        backend:
          service:
            name: enrolement-service
            port:
              number: 8082
  - host: yoloooo.com
    http:
        paths:
        - pathType: Prefix
          path: /front
          backend:
            service:
              name: front-service
              port:
                number: 80
  - host: yoloooo.com
    http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: chat-service
              port:
                number: 9000
                 